### ISSUE TITLE
E402 should be ignored in flake8.ini 

### ISSUE THREAD

**Issue by mo29cg** [nvdaaddons/AddonTemplate#35]
E402 (which is for "module level import not at top of file") should be added to the ignored list in flake8.ini.

because it is common to import external libraries like this,
```
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "site-packages"))
from . import languages as languages
```

This causes E402 error, and there isn't really other way to use external libraries within nvda add-ons

**Comment by josephsl** [comment]
Use of Flake8 is in flux at the moment as folks are thinking about code style and how to handle tab-based indentation while using newer Flake8 or other tools.

Tanks.

**Comment by lukaszgo1** [comment]
The presented code snipped is an antipattern for at  least two reasons:
- You are not cleaning up after yourself i.e. the added directory remains in `sys.path` even after imports
- If at all possible new import locations should be appended to `sys.path`, not added in front, to avoid module conflicts (for one example where this turned out to be problematic see https://github.com/nvaccess/nvda/pull/14812)

If you often have to add to `sys.path` before importing what we did at my previous workplace was a simple context manager, which adds the specified directory to path, imports are done inside the `with` block, and at the end the appended directory is removed. This also silences Flake8, since it understands that if imports are done in the `with` block some action has to occur before them.

I suggest to either use something like this, or ignore the error on a line by line basis.

**Comment by josephsl** [comment]
Hi,

January 2024 update: did the advice help you? If yes, I vote to close this issue.

Thanks.

**Comment by josephsl** [comment]
Hi,

This issue wil become no longer relevant once Flake8 is replaced with Ruff in the add-on tempalte.

Thanks.

**Comment by mo29cg** [comment]
Hey, my addon code is finally improved folowing your advice, thanks!
I'm using this contextmanager.

```
import sys
import os
from contextlib import contextmanager


@contextmanager
def temporary_sys_path():
    original_sys_path = sys.path.copy()
    package_path = os.path.join(os.path.dirname(__file__), "site-packages")
    sys.path.insert(0, package_path)
    try:
        yield
    finally:
        sys.path = original_sys_path

```

**Comment by josephsl** [comment]
Hi,

Closing for now - try with Ruff as well. Thanks.
